# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addProductBatchDetailView.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class AddProductBatchDetailWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1163, 763)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setContentsMargins(350, 30, 350, 30)
        self.formLayout_2.setHorizontalSpacing(7)
        self.formLayout_2.setVerticalSpacing(12)
        self.formLayout_2.setObjectName("formLayout_2")
        self.iDLabel = QtWidgets.QLabel(Form)
        self.iDLabel.setObjectName("iDLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.iDLabel)
        self.batchID = QtWidgets.QLineEdit(Form)
        self.batchID.setObjectName("batchID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.batchID)
        self.iDLabel_2 = QtWidgets.QLabel(Form)
        self.iDLabel_2.setObjectName("iDLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.iDLabel_2)
        self.productID = QtWidgets.QComboBox(Form)
        self.productID.setObjectName("productID")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.productID)
        self.Label = QtWidgets.QLabel(Form)
        self.Label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Label.setObjectName("Label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.batchNO = QtWidgets.QLineEdit(Form)
        self.batchNO.setObjectName("batchNO")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.batchNO)
        self.Label_2 = QtWidgets.QLabel(Form)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.deliverDate = QtWidgets.QDateEdit(Form)
        self.deliverDate.setObjectName("deliverDate")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.deliverDate)
        self.Label_3 = QtWidgets.QLabel(Form)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.deliverCompanyName = QtWidgets.QLineEdit(Form)
        self.deliverCompanyName.setObjectName("deliverCompanyName")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.deliverCompanyName)
        self.Label_4 = QtWidgets.QLabel(Form)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.deliverer = QtWidgets.QLineEdit(Form)
        self.deliverer.setObjectName("deliverer")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.deliverer)
        self.Label_5 = QtWidgets.QLabel(Form)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.receiveCompanyName = QtWidgets.QLineEdit(Form)
        self.receiveCompanyName.setObjectName("receiveCompanyName")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.receiveCompanyName)
        self.Label_6 = QtWidgets.QLabel(Form)
        self.Label_6.setObjectName("Label_6")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.receiver = QtWidgets.QLineEdit(Form)
        self.receiver.setObjectName("receiver")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.receiver)
        self.iDLabel_3 = QtWidgets.QLabel(Form)
        self.iDLabel_3.setObjectName("iDLabel_3")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.iDLabel_3)
        self.createID = QtWidgets.QLineEdit(Form)
        self.createID.setObjectName("createID")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.createID)
        self.Label_7 = QtWidgets.QLabel(Form)
        self.Label_7.setObjectName("Label_7")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.createTime = QtWidgets.QLineEdit(Form)
        self.createTime.setObjectName("createTime")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.createTime)
        self.Label_8 = QtWidgets.QLabel(Form)
        self.Label_8.setObjectName("Label_8")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.updateID = QtWidgets.QLineEdit(Form)
        self.updateID.setObjectName("updateID")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.updateID)
        self.Label_9 = QtWidgets.QLabel(Form)
        self.Label_9.setObjectName("Label_9")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.updateTime = QtWidgets.QLineEdit(Form)
        self.updateTime.setObjectName("updateTime")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.updateTime)
        self.Label_10 = QtWidgets.QLabel(Form)
        self.Label_10.setObjectName("Label_10")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(500, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        spacerItem3 = QtWidgets.QSpacerItem(500, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "产品批次新建"))
        self.iDLabel.setText(_translate("Form", "ID："))
        self.iDLabel_2.setText(_translate("Form", "产品ID："))
        self.Label.setText(_translate("Form", "批次号:"))
        self.Label_2.setText(_translate("Form", "交付日期:"))
        self.Label_3.setText(_translate("Form", "交付单位："))
        self.Label_4.setText(_translate("Form", "交付人员："))
        self.Label_5.setText(_translate("Form", "接收单位:"))
        self.Label_6.setText(_translate("Form", "接收人员："))
        self.iDLabel_3.setText(_translate("Form", "创建人员ID"))
        self.Label_7.setText(_translate("Form", "创建时间："))
        self.Label_8.setText(_translate("Form", "修改人员ID:"))
        self.Label_9.setText(_translate("Form", "修改时间"))
        self.Label_10.setText(_translate("Form", "备注："))
        self.pushButton_3.setText(_translate("Form", "保存"))
        self.pushButton_4.setText(_translate("Form", "取消"))
